### ISSUE TITLE
[DATASET] CaSiNo: A Corpus of CampSite Negotiation Dialogues

### ISSUE THREAD

**Issue by kushalchawla** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#100]
Hello,

I request you to add our dataset to the repository. 

All the requested information about the dataset can be found at [this](https://drive.google.com/drive/folders/1haMX0eVAn3kmq3v90W9VGUk2W2m8FfJc?usp=sharing) link. Please let me know if you need anything else from my end.

Hoping for a prompt response,
Thank you!

**Comment by Khonzoda** [comment]
Hi,

Thank you very much! We added CaSiNo corpus to ConvoKit. Here is its [documentation page](https://convokit.cornell.edu/documentation/casino-corpus.html) based on the notes you provided. Please reach out with any questions/concerns.

Thanks again :)

**Comment by kushalchawla** [comment]
Hey @Khonzoda. This looks great. Thanks a lot for including the dataset. :)

**Comment by calebchiam** [comment]
@all-contributors please add @kushalchawla for data

**Comment by calebchiam** [comment]
@all-contributors please add @kushalchawla for data
