### ISSUE TITLE
Set up all-contributors

### ISSUE THREAD

**Issue by calebchiam** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#101]
https://allcontributors.org

**Comment by calebchiam** [comment]
Initial test:

@all-contributors please add @calebchiam for infra

**Comment by calebchiam** [comment]
@all-contributors please add @cristiandnm for code, data, ideas, maintenance, doc, review

**Comment by calebchiam** [comment]
@all-contributors please add @qema for code, data, ideas, maintenance, doc, review

**Comment by calebchiam** [comment]
@all-contributors please add @tisjune for code, data, ideas, maintenance, doc, review

**Comment by calebchiam** [comment]
@all-contributors please add @jpwchang for code, data, ideas, maintenance, doc, review

**Comment by calebchiam** [comment]
@all-contributors please add @liye for code, data, ideas, maintenance, doc, review

**Comment by calebchiam** [comment]
@all-contributors please add @calebchiam for code, data, ideas, maintenance, doc, review

**Comment by calebchiam** [comment]
@all-contributors please add @calebchiam for code, data, ideas, maintenance, doc, review

**Comment by seanzhangkx8** [comment]
@all-contributors please add @seanzhangkx8 for code, ideas, maintenance, doc, review
