### ISSUE TITLE
Classify dialogue acts of a new corpus

### ISSUE THREAD

**Issue by angoodkind** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#142]
I wasn't clear about this from the documentation: If I have my own conversational dataset, can I use ConvoKit to automatically label/classify the dialogue acts of each utterance?

**Comment by calebchiam** [comment]
The feature extraction methods provided by ConvoKit are those listed under "The toolkit currently implements features for:" in the README. So we don't provide a Dialog Act classifier in ConvoKit, though you could certainly train a classifier on the Switchboard Dialog Act Corpus.

**Comment by angoodkind** [comment]
Thanks
