### ISSUE TITLE
Annotate utterances.jsonl

### ISSUE THREAD

**Issue by vr25** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#148]
Hi,

I am planning to annotate the text in `utterances.jsonl` file with custom entities using the external UBI AI annotation tool. This will change the original structure of the convokit dataset. 

So, how do I annotate it and also retain the dataset structure?

Any help would be appreciated.

Thanks!

**Comment by calebchiam** [comment]
Hi, have you tried loading it as a corpus and adding the custom entities as utterance metadata? You can dump (aka save) the corpus once you're done.

**Comment by vr25** [comment]
Thanks @calebchiam for your prompt response. No, I haven't tried that. So, I will look into it and ask further questions.
