### ISSUE TITLE
Multi-word hedges defined but can't be detected

### ISSUE THREAD

**Issue by alexdiment** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#149]
Hi, thanks for the great tool!

There are some multi-word hedges ("certain extent", "from my perspective", "in my view" etc.) [listed](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/8c35ab2ed3e2c78d1111177349017c631bfb789e/convokit/politeness_collections/politeness_api/features/politeness_strategies.py#L20) in politeness_collections/politeness_api/features/politeness_strategies.py. They seem to be incompatible with the way the detection functions are defined (`has_hedge = lambda p: check_word(p, tok=hedges)` and `hashedges = lambda p: check_word(p, dep=["nsubj"], up_tok=hedges)`). The functions expect single tokens and don't just do string matching.

Can be confirmed by trying to get such hedges detected:
```
from convokit import PolitenessStrategies
import en_core_web_sm

spacy_nlp = en_core_web_sm.load(disable=['ner'])
ps = PolitenessStrategies()
utt = ps.transform_utterance('to my knowledge, this is not the case', spacy_nlp=spacy_nlp, markers=True)
print(utt.meta['politeness_markers'])
```

Seems like such hedges would require manual rule definition, similarly to "I apologize" defined as `check_word(p, tok=["i"], up_tok=["apologize"], dep=["nsubj"])`. So, the "certain extent" hedge would need to be formulated as `check_word(p, tok=["certain"], up_tok=["extent"], dep=["amod"])`. This won't help in the cases of more than two words ("from my perspective"), as `check_word` seems to only work with pairs of tokens. Three-word cases would require customizing the `check_word` function as well?

**Comment by cristiandnm** [comment]
Thanks for reaching out.  You are correct that politeness_strategies.py does not extract multi-word hedges.  Your proposed approach would work if you want to directly modify that function.  However, setting strategy_collection = "politeness_local" when constructing the PolitenessStrategies transformer should also work.   

This is the code that is run in the background when using strategy_collection = "politeness_local", if you want to dig in further you'll see that it has special functionality for dealing with ngrams:

https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/8c35ab2ed3e2c78d1111177349017c631bfb789e/convokit/politeness_collections/politeness_local/strategy_extractor.py

Take a look and let us know whether it works for you.

**Comment by alexdiment** [comment]
Great, thanks a lot!
