### ISSUE TITLE
Estimated arrival of linguistic diversity code?

### ISSUE THREAD

**Issue by kstats** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#22]
I read your paper on The Linguistic Development of Mental Health Counselors and am interested in trying your diversity technique on my own dataset.  Is there an estimate for when the code will be published?  Thank you!

**Comment by tisjune** [comment]
Thanks for your interest in the code and sorry for the delay -- we're hoping to release the code by the end of September.

**Comment by tisjune** [comment]
Hi there, we've just released a new version of convokit (pip install upgrade) that has the linguistic diversity code, along with some other functionality. https://zissou.infosci.cornell.edu/convokit/documentation/userConvoDiversity.html
Let me know if you have any questions. In particular, this code was developed in large part with the particular dataset we ran it on in mind, so the parameters might take some toggling, and in general any suggestions to make it more generalizeable would be awesome!
