### ISSUE TITLE
[datasets] Chromium Conversations Corpus

### ISSUE THREAD

**Issue by meyersbs** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#23]
## Dataset Information

**Name:** Chromium Conversations Corpus
**Description:** Almost 1.5 million conversations posted by developers reviewing proposed code changes in the [Chromium](https://www.chromium.org/Home) project.
**Full Description:** https://zenodo.org/record/2590548
**Data License:** [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/legalcode)
**Contact Information:** Benjamin S. Meyers (bsm9339@rit.edu)

## Dataset Publication

Benjamin S. Meyers, Nuthan Munaiah, Emily Prud'hommeaux, Andrew Meneely, Cecilia O. Alm, Josephine Wolff, and Pradeep Murukannaiah. **A Dataset for Identifying Actionable Feedback in Collaborative Software Development.** Proceedings of the 2018 Meeting for the Association for Computational Linguistics (ACL). Melbourne, Australia. http://www.aclweb.org/anthology/P18-2021

## Dataset Statistics

**Number of Utterances:** 2,853,498
**Number of Developers:** 4,842
**Number of Conversations:** 1,484,843

## Utterance Annotations

Each utterance corresponds to a comment in the Chromium project and has some associated pre-calculated linguistic metrics:

- **yngve_score:** The maximum Yngve score of sentences in the code review comment
- **frazier_score:** The maximum Frazier score of sentences in the code review comment
- **pdensity:** The Propositional Density score of the code review comment
- **cdensity:** The Content Density score of the code review comment
- **has_doxastic:** Binary indicator of presence of a sentence with doxastic uncertainty in the code review comment
- **has_epistemic:** Binary indicator of presence of a sentence with epistemic uncertainty in the code review comment
- **has_conditional:** Binary indicator of presence of a sentence with conditional uncertainty in the code review comment
- **has_investigative:** Binary indicator of presence of a sentence with investigative uncertainty in the code review comment
- **has_uncertainty:** Binary indicator of presence of a sentence with any uncertainty in the code review comment
- **min_formality:** Minimum of the formality of sentences in the code review comment
- **max_formality:** Maximum of the formality of sentences in the code review comment

## Conversation Metadata

Each conversation has the associated metadata:

- **review_id:** Unique identifier of a code review in the Chromium project. The URL `https://codereview.chromium.org/<review_id>` may be used to access the review online
- **patchset_id:** Unique identifier of a code review patchset (i.e., collection of changes to the source code) associated with a review
- **patch_id:** Unique identifier of a code review patch (i.e., individual change to the source code) associated with a patchset
- **file_path:** The path to the file being modified in the patch
- **line_number:** The line number in the file at which the comment was posted

## Example Usage

See this [example script](https://gist.github.com/meyersbs/6ebd7b0ed83de2a820fd2edff45445aa)!

## Download

[Corpus](http://people.rc.rit.edu/~bsm9339/corpora/chromium_convokit/chromium_convo_corpus.zip) link.

**Comment by calebchiam** [comment]
Thanks, Benjamin! We will integrate this into ConvoKit in the next few days.

**Comment by calebchiam** [comment]
Integrated into ConvoKit. Corpus now downloadable as 'chromium-corpus'.
