### ISSUE TITLE
[datasets] change-my-view-corpus

### ISSUE THREAD

**Issue by szmurlo** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#27]
# change-my-view-corpus

This corpus contains a metadata-rich subset of conversations made in the ChangeMyView subreddit between 2013/01/01-2015/05/07. Each convokit conversation in this dataset is the corresponding full comment thread of an original post made to changemyview. Within each full thread are comments made by redditors (with the objective of the subreddit to change the opinion of the original post). There are 34911 Users, 293297 Utterances, and 3051 Conversations.

## Dataset Details

- To see the original posts in each conversation, note that the 'root' metadata of an Utterance (i.e. Reddit comment) would be the same as the 'id' metadata (this only holds true for original posts).
- The main indicator of interest in this data is whether an argument succeeded in changing the original poster's (OP's) view. To denote a successful argument: the "success" field of an utterance takes the value of 1 (these utterances were the comments in the original post that succeeded in changing OP's mind), or the "success" field takes the value of 0 (this collection of utterances were a comment thread that are similar in nature to a successful argument in the full thread(matched on pair_id), but this argument failed to change OP's mind -- See section 4 of the cited paper for selection criteria of successful/unsuccessful arguments. All other comments take a 'success' value of None.
- Note for pair_ids: the successful-unsuccessful argument pairs originally compiled by the authors are not unique at the Conversation-level nor Utterance-level (i.e. the original posts to the ChangeMyView subreddit can have multiple successful-unsuccessful comment pairs in their full-comment threads **and** some comments can have multiple opposing pairs -- see the relevant metadata fields at Conversation-level and Utterance-level below).
- Note on missing data: 530 'Reddit comments' were included from the original data which did not have text nor an author. These were included for completeness, each utterance has User(name='[missing]').

### User-level information:
	- contains information about each user (i.e. Redditor)
	- fields: 
		- meta: empty dict (note: the original 'all' data file may have more information on individual Redditors, but the authors' pair_data only had comment-level data, therefore, we included the User-level data because each Redditor has a unique identifier: their Reddit username)

### Utterance-level information:
	- contains information about every comment posted in the changemyview subreddit posts that were collected for successful/unsuccessful arguments in Section 4 of the cited paper above
	- fields:
		- id, unique comment identification provided by Reddit
		- user, unique user id (i.e. Reddit username)
		- root, comment identifier of the original post in the thread that this comment was posted in
		- reply_to, unique identifier of the comment that this comment was in direct response to
		- timestamp, comment post time provided by Reddit API
		- text, the full text (in string) of the comment
		- meta:
			- success, an indicator taking the value of 1 if the comment was part of a successful argument thread (i.e. an argument thread that changed the OP's mind), 0 if unsuccessful, and None if not part of either a successful or unsuccessful thread.
			- pair_ids, every successful-unsuccessful argument pair originally compiled by the authors has a unique pair_id. However, it is important to note that not every argument is unique (i.e. a single negative argument within a conversation could have two opposing positive arguments, which necessitates two corresponding pair_ids. Therefore, pair_ids is a list).
			- replies, a list of comment ids that respond directly to the current comment. For the OP post in the thread, this was constructed by selecting all comment ids with a "reply_to" field equal to the original post id (this was necessary because the original data provided by the authors did not include all the children of the OP post in their data format). For all comments besides the original post, the "replies" field was originally provided by Reddit API.
			- originally provided by Reddit API: author_flair_text, author_flair_css_class, banned_by, controversiality, edited, distinguished, user_reports, ups, downs, subreddit_id, subreddit, score_hidden, score, saved, report_reasons, mod_reports,  num_reports, likes, gilded,approved_by (see the [Reddit API](https://www.reddit.com/dev/api/) for more information)

### Conversation-level
	- fields:
		- _owner: Corpus object: the 'Change My View Corpus'
		- _id: unique comment identifier of the original post, which started the conversation thread
		- _utterance_ids: unique comment identifiers of every Utterance (i.e. comment) in the Reddit thread
		- _meta:
			- op-userID, the Reddit username of the original poster (OP)
			- op-text-body, the text of OP's first post (starting the conversation)
			- op-title, the title of OP's first post 
			- pair_ids, a list of all the successful-unsuccessful pairs in the conversation (to subset the successful from unsuccessful Utterances, refer to the "success" metadata indicator in Utterance-level meta (above))
			- train, an indicator taking the value of 1 if this conversation was included in the training data subset of the original paper and 0 if it was included in the holdout set.

### Corpus-level information
	- fields:
		- meta:
			- name, 'Change My View Corpus'

## Usage
data available on [Google Drive](https://drive.google.com/drive/folders/1xZewEwlYKWfKSyjhVt_f1nCO6aKaO27S?usp=sharing)

[Convert Jupyter Notebook](https://github.com/szmurlo/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/change-my-view-corpus/convert.ipynb) -- takes original dataset and converts it to convokit format

[Simple Statistics Jupyter Notebook](https://github.com/szmurlo/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/Simple%20statistics%20from%20a%20subset%20of%20the%20change-my-view%20corpus.ipynb)  -- demonstrates how to subset the data into successful and unsuccessful arguments (as described in Section 4 of the original paper) and provides basic statistics about their respective comments.

## Notes
License: see  [data source](https://chenhaot.com/pages/changemyview.html) for details.

The data available was originally used in the following publication (cite if using the data):

Title: Winning Arguments: Interaction Dynamics and Persuasion Strategies in Good-faith Online Discussions
Authors: Chenhao Tan and Vlad Niculae and Cristian Danescu-Niculescu-Mizil and Lillian Lee
Year: 2016
Proceedings of WWW

## Contact
Corpus converted into ConvoKit format by [Andrew Szmurlo](as3934@cornell.edu) and Meir Friedenberg

**Comment by calebchiam** [comment]
Hey Andrew,

Thanks for your work on the change-my-view corpus! I've currently reviewing it for integration into ConvoKit.

I have some feedback and questions that we should discuss before integration:

1. Could you revise either your dataset issue or your README to the style [here](https://zissou.infosci.cornell.edu/convokit/documentation/chromium.html) or [here](https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/friends-corpus/README.md)? You're fine information-wise (good detail too), but it's split between your dataset issue and your README (which contains some other comments and writing in the first-person that would not fit on the dataset description page.) I think the first-person comments are good for explaining certain decisions, but this could be phrased more formally perhaps or placed elsewhere.

For example, the note regarding how to 'expand the arguments to include all conversant' might be a better fit for the conversion notebook instead.

You should include documentation for the metadata from the Reddit API as well. (For some of them, you can copy it off the [reddit-corpus dataset documentation](https://zissou.infosci.cornell.edu/convokit/documentation/subreddit.html).

2. At the moment, the corpus includes only utterances from threads from the training period, but not the holdout period. What is the motivation for this and would it be possible to include the rest of the data from the original dataset in this corpus as well? I believe the ideal scenario would be that the entirety of the original dataset is converted to the corpus format - with metadata denoting the status of specific conversations / utterances as coming from the 'training' or 'holdout' periods perhaps.

3. You added a 'replies' field to the Utterance metadata for Utterances that correspond to the OP post. This is a good instinct, but I'm wondering if this is necessary because couldn't you do the same with `corpus.get_conversation(utt_id).get_utterance_ids()`? (since utt_id == convo_id for the OP post.) 

In any case, 'replies' seems to be a Conversation-level feature rather than an Utterance-level feature.

4. During the conversion process, I see that 462 comments were excluded because they were missing one of the common attributes. This is a common issue with Reddit data but I think it would be more ideal to keep the data in and put a placeholder 'None' value for the missing attributes

4. MINOR: The utterance timestamps seem to be floats right now. Could you convert them to ints?

Having worked with this dataset extensively, you and Meir are more familiar with it than I am, so do let me know if these changes make sense. Thanks!

**Comment by szmurlo** [comment]
Thanks Caleb, I'll take a look this weekend.

Hope you have a good fall break,
Andrew

**Comment by szmurlo** [comment]
Hi Caleb,
Here's an update to your requests:

   1. *Could you revise either your dataset issue or your README to the
   style here
   <https://zissou.infosci.cornell.edu/convokit/documentation/chromium.html>
or here
   <https://github.com/emtseng/Cornell-Conversational-Analysis-Toolkit/blob/master/datasets/friends-corpus/README.md>?
   You're fine information-wise (good detail too), but it's split between your
   dataset issue and your README (which contains some other comments and
   writing in the first-person that would not fit on the dataset description
   page.) I think the first-person comments are good for explaining certain
   decisions, but this could be phrased more formally perhaps or placed
   elsewhere.     **For example, the note regarding how to 'expand the
   arguments to include all conversant' might be a better fit for the
   conversion notebook instead.     **You should include documentation for
   the metadata from the Reddit API as well. (For some of them, you can copy
   it off the reddit-corpus dataset documentation
   <https://zissou.infosci.cornell.edu/convokit/documentation/subreddit.html>.*

I've updated the issue to reflect Emily's README (Friends dataset) and I've
moved the first-person notes/process comments/data expansion methods to a
Notes section in the convert file as you suggested. I also provided a link
to the Reddit API. Note: the authors originally didn't include any
information on these 'Reddit Provided' variables, so I didn't have much to
work with. DNM suggested that I combine all of these into a single list
just for brevity in the readme.

   1.

   *At the moment, the corpus includes only utterances from threads from
   the training period, but not the holdout period. What is the motivation for
   this and would it be possible to include the rest of the data from the
   original dataset in this corpus as well? I believe the ideal scenario would
   be that the entirety of the original dataset is converted to the corpus
   format - with metadata denoting the status of specific conversations /
   utterances as coming from the 'training' or 'holdout' periods perhaps**.*

This was a good catch, thanks. I've added in the holdout data and included
a conversation-level metadata field 'train' which indicates whether the
conversation was in the training data (1) or holdout data (0). Note: we
only used and converted to convokit the "pair data" from section 4 of the
paper. Their full data is just the CMV subreddit
from 2013/01/01-2015/05/07, and I believe you've already included the
entire CMV subreddit in the Reddit Corpus.

   1.

   *You added a 'replies' field to the Utterance metadata for Utterances
   that correspond to the OP post. This is a good instinct, but I'm wondering
   if this is necessary because couldn't you do the same
   with corpus.get_conversation(utt_id).get_utterance_ids()? (since utt_id ==
   convo_id for the OP post.) **In any case, 'replies' seems to be a
   Conversation-level feature rather than an Utterance-level feature.*

  Note: the comments listed in the 'replies' metadata are only comments
made in direct response to a comment. This is separate from all the
comments in a conversation tree, which you can get from
"corpus.get_conversation(utt_id).get_utterance_ids()"   It is unique at the
comment-level, not the conversation-level. I apologize that the readme
wasn't clear, and I have updated it to reflect this.


   1.

   *During the conversion process, I see that 462 comments were excluded
   because they were missing one of the common attributes. This is a common
   issue with Reddit data but I think it would be more ideal to keep the data
   in and put a placeholder 'None' value for the missing attributes *

Even though they lack text, I had originally planned to add these, but
since they also are missing an author, the
Corpus(utterances=utterance_list) function breaks down because for these
comments, User=None.

   1.

   *MINOR: The utterance timestamps seem to be floats right now. Could you
   convert them to ints? *Fixed.

**Comment by calebchiam** [comment]
Thanks Andrew, these changes look good.

For #4, I would recommend instantiating a User(name='[missing]') and passing that as the argument. Just add a note about this in the conversion documentation and above in the description.

**Comment by szmurlo** [comment]
Fixed. The 530 comments are now included in the data -- I've updated the
convert nb to mention this and made a note in the issue above (under
Dataset Details).

**Comment by calebchiam** [comment]
Thanks for the prompt follow-up! Pleased to inform you that the corpus has been [successfully integrated into ConvoKit](https://zissou.infosci.cornell.edu/convokit/documentation/winning.html) (:

**Comment by szmurlo** [comment]
Awesome! Thanks Caleb.

**Comment by calebchiam** [comment]
@all-contributors please add @szmurlo for data
