### ISSUE TITLE
[dataset] IQ2 Debates Corpus

### ISSUE THREAD

**Issue by lucasvanbramer** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#30]
IQ2 Debate ConvoKit Formatted Dataset
==============================================

This dataset contains a set of json files that have been formatted to fit the Convokit format. There are 108 debates in all, that were held between September 2006 and September 2015. We aim to maximize the information that is retained when converting this to a ConvoKit format.

The original dataset is taken from http://tisjune.github.io/research/iq2 and featured in the paper Zhang, Justine, et al. Conversational Flow in Oxford-Style Debates. Proceedings of the 2016 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies, 2016, doi:10.18653/v1/n16-1017.

Corpus translated into ConvoKit format by Lucas Van Bramer and Marianne Aubin Le Quere.

Dataset details
==============================================

User-level information

Users in this dataset are the speakers during the debate. The most prominent speakers are those that are listed in the initial dataset as being either ‘for’ a position, ‘against’ it, or a ‘moderator.’ However, there are also other speakers that do not fit into these categories, such as a ‘host’ or a ‘panelist.’ Our user corpus also includes these speaker types. 

We provide:
- stance: whether they are ‘for’ or ‘against’ a proposition. Will be None if they are impartial such as a moderator or host.
- bio: if available, full length bio of speaker
- bio_short: if available, short bio of speaker
==============================================

Utterance-level information

Each utterance is a continuous speaking turn of a single speaker. 

We provide:
	- nontext: this is a dictionary of audience reaction
	- segment: which segment of the debate the utterance was spoken during
	- speakertype: the type of speaker who is saying the utterance
	- debateid: the unique id of the debate

==============================================
Conversation-level information

Our conversations are indexed by the first utterance of a conversation. This means each debate is represented as one conversation. We also provide debate-level metadata at the conversation level as they are equivalent for our dataset.

We provide:
	- summary: a summary of the debate
	- title: the title of the debate
	- date: the date of the debate
	- url: the url where the debate can be accessed
	- winner: indicates which side won a debate, 'for,' 'against,' or 'tie'
	- results: a full breakdown of the starting and ending positions of the audience in the debates. These are all represented as percentages. The 'results' json file contains 3 dicts with the following metadata:
		- breakdown: entries in this dictionary take the form position1_position2, where position1 is the position at the start of the debate and position2 is the position at the end of the debate. This breakdown is not available for the earlier debates. The entries are thus:
			- against_against
			- against_for
			- against_undecided
			- undecided_against
			- undecided_for
			- undecided_undecided
			- for_against
			- for_for
			- for_undecided
		- pre: percentage of audience that voted 'for,' 'against,' or 'undecided' at the beginning of the debate.
		- post: percentage of audience that voted 'for,' 'against,' or 'undecided' at the end of the debate.
		This results breakdown follows the same structure as the original dataset.
	- speakers: the official speakers of the debate (note our users corpus is more expansive than this definition)

==============================================
Stats:
	number of Users: 471
	number of Utterances: 26562
	number of Conversations: 108

[iq2_corpus_convokit.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3716862/iq2_corpus_convokit.zip)

**Comment by tisjune** [comment]
Hi,
Thanks for your work with converting the IQ2 corpus! I had a few questions and comments:

Description:
- You can abbreviate or reformat the citation to match what's on the website: i.e., abbreviate the conference name as NAACL, remove the DOI.

Users:
- Are there users who participate in multiple debates? In any case, it's not a-priori given that each user will only be associated with one stance, and stance may not be something that makes sense independent of a debate. You could either maintain a dictionary of debate-->stance for each user, or put the side information as metadata at the conversation level.

Utterances:
- currently the utterance IDs seem to be stored as strings. I think they're actually ints though, so you should store them as such.
- reply_tos should be None, not -1, if the utterance is not a reply.
- perhaps expand on the descriptions of the nontext and segment fields in the readme to match the level of detail in the original readme.

Conversations:
- maybe include the debateids as meta fields in conversations, as opposed to/in addition to per utterance, since this appears to be a conversation-level item.
- is there a particular reason for repeating the speaker bios, if you've already included them per-user? (if a multi-debate user changes bios, then that might be one reason, but then the bio is no longer a user-level property, in the same way that stance should be indexed by user,conversation).

Let me know if these comments make sense, and thanks!

**Comment by cristiandnm** [comment]
Lucas and Team,

Checking in on your status on the items Justine pointed out.

**Comment by lucasvanbramer** [comment]
Hi there,

This should be done by end of day today - I do not anticipate any major
issues with accommodating these changes, but will post if I do.

Best,
Lucas

**Comment by lucasvanbramer** [comment]
[iq2_corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3747284/iq2_corpus.zip)
I made the requested changes and added a new piece of metadata about paragraph breaks in the original text given that we eliminated paragraphs (concatenate them) so that the nontext metadata is useful. Please let me know if this all looks good - thanks!

**Comment by tisjune** [comment]
Thanks! I've added this dataset to convokit. Just a small thing -- do you have contact information you'd be willing to provide in the readme? (e.g., see the contact info provided at the bottom of this doc: https://zissou.infosci.cornell.edu/convokit/documentation/coarseDiscourse.html)

**Comment by lucasvanbramer** [comment]
Sure - I'd be happy to have my Cornell email listed. ljv32@cornell.edu

**Comment by tisjune** [comment]
thanks! I added this email and will close the issue; please let me know if Marianne would also like her contact info to be added, or if you spot anything off about the corpus we've released or the documentation.

**Comment by tisjune** [comment]
Sorry -- just a quick question -- could you link me to the latest version of your data conversion code, so I can add that to the repo too? Thanks!

**Comment by lucasvanbramer** [comment]
Sure thing! Attached is the conversion code (in a zip because Github doesn't allow ipynb uploads). 


[iq2_to_convokit.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/3764851/iq2_to_convokit.zip)

**Comment by tisjune** [comment]
great, thanks! closing this issue now.

**Comment by calebchiam** [comment]
@all-contributors please add @lucasvanbramer for data

**Comment by calebchiam** [comment]
@all-contributors please add @maubinle for data
