### ISSUE TITLE
Bug in Utterance, User, Conversation, __eq__ methods

### ISSUE THREAD

**Issue by jschluger** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#33]
The `__eq__` methods for Utterance, User, Conversation classes of convokit may fail if the object being compared to is the wrong type, or None.

For example this code:
```
for convo in corpus.iter_conversations():
    if convo == None:
        print('convo is none')
```
outputs:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-15-4ad415793465> in <module>
     10 for convo in corpus.iter_conversations():
     11     a = None
---> 12     if convo == None:
     13         print('error')
     14     else:

~/anaconda3/envs/convo/lib/python3.7/site-packages/convokit/model/conversation.py in __eq__(self, other)
    126 
    127     def __eq__(self, other):
--> 128         return self.__dict__ == other.__dict__
    129 
    130     def __repr__(self):

AttributeError: 'NoneType' object has no attribute '__dict__'
```
when it should really return the same value as `convo is None`.

**Comment by calebchiam** [comment]
Hi Jack, thanks for catching this. I've pushed a fix for this so this should be corrected in the next release.

In the meantime, as you've noted, you can use (the more pythonic) "if convo is None" to check if an object is present.

Do let us know if you encounter any other issues!

**Comment by calebchiam** [comment]
@all-contributors please add @jschluger for bug

**Comment by calebchiam** [comment]
@all-contributors please add @jschluger for bug
