### ISSUE TITLE
Working on small conversational corpus

### ISSUE THREAD

**Issue by bluemonk482** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#34]
This is a great tool for analysing QA data! Thanks. However I have a rather small data set of 50 conversations (two people Q&As, transcribed from audio recordings). It seems both `PromptTypes` and `PromptTypeWrapper` are not made for my data? Is there any settings or parameters I should change to make it use for my data. 

```
from convokit.prompt_types import PromptTypes

def question_filter(utt, aux_input={}):
    return utt.meta['is_question']
def response_filter(utt, aux_input={}):
    return (not utt.meta['is_question']) and (utt.reply_to is not None)


pt = PromptTypes(n_types=8, prompt_field='motifs', ref_field='arcs_censored', 
                 prompt_filter=question_filter, ref_filter=response_filter,
                 prompt_transform_field='motifs__sink',
                 output_field='prompt_types',
    random_state=1000, verbosity=1)

pt.fit(corpus)
```

> fitting 0 input pairs
> fitting ref tfidf model
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-73-d0c524fd4289> in <module>
>      13     random_state=1000, verbosity=1)
>      14 
> ---> 15 pt.fit(corpus)
> 
> /mnt/sdb/env1/lib/python3.6/site-packages/convokit/prompt_types/promptTypes.py in fit(self, corpus, y)
>     121                                                                 self.snip_first_dim, self.prompt__tfidf_min_df, self.prompt__tfidf_max_df,
>     122                                                                 self.ref__tfidf_min_df, self.ref__tfidf_max_df,
> --> 123 								self.svd__n_components, self.random_state, self.verbosity)
>     124                 self.train_results['prompt_ids'], self.train_results['prompt_vects'],\
>     125                         self.train_results['ref_ids'], self.train_results['ref_vects'] = self._get_embeddings(corpus)
> 
> /mnt/sdb/env1/lib/python3.6/site-packages/convokit/prompt_types/promptTypes.py in fit_prompt_embedding_model(prompt_input, ref_input, snip_first_dim, prompt__tfidf_min_df, prompt__tfidf_max_df, ref__tfidf_min_df, ref__tfidf_max_df, svd__n_components, random_state, verbosity)
>     451                 token_pattern=r'(?u)(\S+)'
>     452 	)
> --> 453         ref_vect = ref_tfidf_model.fit_transform(ref_input)
>     454 
>     455         if verbosity > 0:
> 
> /mnt/sdb/env1/lib/python3.6/site-packages/sklearn/feature_extraction/text.py in fit_transform(self, raw_documents, y)
>    1650         """
>    1651         self._check_params()
> -> 1652         X = super().fit_transform(raw_documents)
>    1653         self._tfidf.fit(X)
>    1654         # X is already a transformed view of raw_documents so
> 
> /mnt/sdb/env1/lib/python3.6/site-packages/sklearn/feature_extraction/text.py in fit_transform(self, raw_documents, y)
>    1056 
>    1057         vocabulary, X = self._count_vocab(raw_documents,
> -> 1058                                           self.fixed_vocabulary_)
>    1059 
>    1060         if self.binary:
> 
> /mnt/sdb/env1/lib/python3.6/site-packages/sklearn/feature_extraction/text.py in _count_vocab(self, raw_documents, fixed_vocab)
>     987             vocabulary = dict(vocabulary)
>     988             if not vocabulary:
> --> 989                 raise ValueError("empty vocabulary; perhaps the documents only"
>     990                                  " contain stop words")
>     991 
> 
> ValueError: empty vocabulary; perhaps the documents only contain stop words

**Comment by tisjune** [comment]
Hi! Sorry you're having trouble with this code. Just to check -- does your corpus have the field 'is_question' in the utterance metadata filled out (such that questions have is_question=True and non-questions have is_question=False)? The prompt_filter and ref_filter arguments currently check for this field and only include question-response pairs if the metadata satisfies these constraints.

Two fixes could be:
1. fill out this metadata field;
2. pass in None to prompt_filter and ref_filter (in this case, the code will use all adjacent pairs of utterances as questions and responses).

**Comment by bluemonk482** [comment]
Thanks for your quick reply Justine! Yes it does have `is_question` and `is_answer` in the `metadata` field:
```
In [7]: utt = corpus.get_utterance('00001')
In [8]: print(utt.meta)
Out [8]: {'is_question': True, 'is_answer': False, 'parsed': [{'rt': 1, 'toks': ... ...
```

Passing in None to prompt_filter and ref_filter gives the same empty vocab error. I think the problem comes from the computation of the motifs. It seems quite a few of my utterances gets empty motifs:

```
In [77]: utt = corpus.get_utterance('140010')
In [78]: utt.get_info('motifs')
Out [79]: []
In [80]: utt.get_info('motifs__sink')
Out [80]: []
```

**Comment by tisjune** [comment]
Got it. Setting the min_support argument lower might help (this is the minimum frequency that a phrasing has to appear in the corpus to be considered, and is currently set to 100 by default).
Alternatively, for small data where maybe there are less well-defined phrasings, replacing both the prompt_field and prompt_transform_field arguments with 'arcs_censored' or 'arcs' could also help (such that the prompt type module is using dependency tree arcs rather than entire phrasings as input representations). 
I'd also check to make sure that the input fields actually exist (e.g., arcs_censored is actually filled in).

**Comment by bluemonk482** [comment]
There are 7000+ utterances in the data set. Also:

```
from convokit.phrasing_motifs import PhrasingMotifs

pm_model = PhrasingMotifs('motifs','question_arcs',min_support=20,fit_filter=question_filter,
                          verbosity=VERBOSITY)

pm_model.fit(corpus)
```

> counting frequent itemsets for 1730 sets
> 	first pass: counting itemsets up to and including 5 items large
> 	second pass: counting itemsets more than 5 items large
> 	second pass: checking 28 sets for itemsets of length 6
> making itemset tree for 176 itemsets
> deduplicating itemsets
> 	finding supersets

**Comment by bluemonk482** [comment]
Thanks @tisjune !! I have tried setting `min_support` to as low as `2`, and replacing both the `prompt_field` and `prompt_transform_field` arguments with 'arcs_censored' or 'arcs'. I am still getting the same empty vocab error...

There are 7000+ utterances in the data set. 
```
noun_pm_model = PhrasingMotifs('motifs_full','question_arcs_full',min_support=2,
                               fit_filter=question_filter, 
                          verbosity=VERBOSITY)
noun_pm_model.fit(corpus)
```

> counting frequent itemsets for 1730 sets
> 	first pass: counting itemsets up to and including 5 items large
> 	second pass: counting itemsets more than 5 items large
> 	second pass: checking 728 sets for itemsets of length 6
> 	second pass: checking 441 sets for itemsets of length 7
> 	second pass: checking 164 sets for itemsets of length 8
> 	second pass: checking 20 sets for itemsets of length 9
> 	second pass: checking 2 sets for itemsets of length 10
> making itemset tree for 15919 itemsets
> deduplicating itemsets
> 	finding supersets
> 	getting supersets for 10000/15919 itemsets

It also has `arcs_censored` in the input field:

>  'arcs_censored': ['is_*', 'so>* so>just so_* so_hear'],
>  'question_arcs': [],
>  'motifs': [],
>  'motifs__sink': [],
>  'root_arcs': ['is_* is_participant is_this this>*',
>   'so>* so>just so_* so_hear'],
>  'question_arcs_full': [],
>  'motifs_full': [],
>  'motifs_full__sink': []}

**Comment by bluemonk482** [comment]
I don't have `info.parsed.jsonl` in my data dir. Not sure if this causes any issues at all..

`corpus.load_info('utterance',['parsed'])` does complains no such file.

**Comment by tisjune** [comment]
from the message you printed out in your first comment it looks like the prompt types component isn't getting any input question-response pairs. so if the fields for prompt and ref you passed in exist, and you've set both prompt and ref filter, then I wonder if your utterances are missing a reply_to field. 

Here's the code that generates the input pairs, for reference: https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/convokit/prompt_types/promptTypes.py#L394 
(the lack of parsed file in the directory shouldn't be a problem if you still have the parses stored in memory)

**Comment by bluemonk482** [comment]
There is a reply_to field.

Actually, I have discovered the cause. Many of the questions do not have a question mark in the end? Can I please confirm that there has to be a question mark in the very last token of each question? Can I disable this? The is_question should be enough for marking which is question right?

**Comment by tisjune** [comment]
If you're calling the QuestionSentences transformer at all, then the questions without a question mark at the end are filtered out. Otherwise, the code will use the is_question field in the utterance metadata. 

If some utterances do have question marks though, then that seems a bit weird. The problem comes from the following line in your output:
> fitting 0 input pairs

which means that somehow *all* of the prompt-response pairs are getting filtered out. 

One other thing I might try is to make sure that the reply_to field and the utterance IDs are both strings (we've had problems where the utterance ID, when read from disk, is a string rather than an int, so there's a mismatch in what was written to disk and what was read). 

Could you try running the following code?  It's the subroutine that extracts the prompt-response pairs, but with an exception removed. If an exception is thrown, this means that the reply_to field is somehow broken in your corpus. If the length of the arrays returned (and hence the value printed) is non-zero, then this means that the problem is with fields being empty (you can toggle this by setting check_nonempty to be True or False in the function call).

```
def get_pair_input(corpus, prompt_field, ref_field, 
		  prompt_filter=lambda x,y,z: True, ref_filter=lambda x,y,z: True, 
		  check_nonempty=True, aux_input={}):
	prompt_ids = []
	prompt_utts = []
	ref_ids = []
	ref_utts = []
	for ref_utt in corpus.iter_utterances():
		if ref_utt.reply_to is None:
			continue
		prompt_utt_id = ref_utt.reply_to
	        prompt_utt = corpus.get_utterance(prompt_utt_id)
		if prompt_filter(prompt_utt, aux_input) \
			and ref_filter(ref_utt, aux_input):

			prompt_input = prompt_utt.get_info(prompt_field)
			ref_input = ref_utt.get_info(ref_field)
			
			if (prompt_input is None) or (ref_input is None):
				continue

			if isinstance(prompt_input, list):
				 prompt_input = '\n'.join(prompt_input)
			if isinstance(ref_input, list):
				 ref_input = '\n'.join(ref_input)

			if (not check_nonempty) or ((len(prompt_input) > 0) and (len(ref_input) > 0)):
				prompt_ids.append(prompt_utt.id)
				prompt_utts.append(prompt_input)
				ref_ids.append(ref_utt.id)
				ref_utts.append(ref_input)
	return prompt_ids, prompt_utts, ref_ids, ref_utts 

prompt_ids, prompt_utts, ref_ids, ref_utts = get_pair_input(corpus, 'arcs_censored', 'arcs_censored', check_nonempty=False)
print(len(prompt_ids))

```

**Comment by bluemonk482** [comment]
Apparently my `reply_to` field had actual utterance strings instead of utterance ids. How embarrassing! After adjusting `xxx__tfidf_min_df` and `svd__n_components`, `PromptTypes` works just fine for me now. Thank you very much for your help @tisjune ! You're awesome and I shall close this issue now.
