### ISSUE TITLE
Appropriate corpus creation for prompt type analysis 

### ISSUE THREAD

**Issue by bluemonk482** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#35]
I have a set of question and answer conversations, but a few of them end with a question instead of answer, and some start with statements instead of question. For example, for one of the conversations, it end with a question, however I have checked the `prompt_types__prompt_repr` if this question, and apparently it has a vector representation but it should not have one right? since it does not have following answer.

Can I please check with you what would be the correct way to create a corpus of this data? Should the corpus strictly follow question->answer->question->answer... ... order? 

Thanks.

**Comment by tisjune** [comment]
There are no strict requirements on the corpus. In this particular case, the code will produce a representation for _any_ utterance (that meets the requirements for the filter that you constructed prompt types with), even if that utterance doesn't have an answer.

**Comment by bluemonk482** [comment]
Thanks @tisjune ! 

> We derive prompt-vectors for the phrasings, which reflect similarities in the subsequent replies that a phrasing prompts.

If a prompt doesn't have a reply (or a question doesn't have an answer), then how is the prompt-reply matrix (or motif-question matrix) computed?

**Comment by tisjune** [comment]
Think of the process as two steps: a training phase and a testing phase. In the training phase, we learn a transformation given the question-reply pairs that do exist in the data, and in the test phase we apply this transformation to every question in the data. The transformation is dependent on the question-reply pairs in the training data, but not on the actual reply that a question gets.

**Comment by bluemonk482** [comment]
Aha! Actually my test data is the same as my training data. So during the training phase, the model simply ignores these questions that don't have replies. But during the test phase, the question vectors are inferred by the learnt model.
