### ISSUE TITLE
Inconsistency between path name for loading and saving a corpus

### ISSUE THREAD

**Issue by jschluger** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#36]
Loading a corpus is done as `corpus = Corpus(filename="corpus_directory")`, which looks for `corpus_directory` in the users current directory.

Saving a corpus is done with `corpus.dump("corpus_directory")` which saves the corpus to `~/.convokit/saved-corpora/`.

An intuitive workflow is for someone to save a corpus to disk and later load it (or load in a later execution of the same program) with code such as:
```
# corpus is a previously defined convokit Corpus object
name = "corpus_name"
corpus.dump(name)
...
new_corpus = Corpus(filename=name)
```
However this will not work, and instead the user would need to do something like
```
# corpus is a previously defined convokit Corpus object
name = "corpus_name"
corpus.dump(name)
...
new_corpus = Corpus(filename="~/.convokit/saved-corpora/"+name)
```
which requires debugging to find where the corpora are stored, and is not intuitive.

**Comment by calebchiam** [comment]
As per the documentation, the correct way to dump a corpus in the local directory is to call `corpus.dump(name, base_path"./")`

However, I do agree that this is potentially confusing and we'll consider changing this. Thanks for raising this!

**Comment by jschluger** [comment]
Ah I see, I was actually on [the data format page](https://zissou.infosci.cornell.edu/convokit/documentation/data_format.html) of the documentation when I got confused by this, so maybe just changing some of the wording there would clear this up for other potential users.
