### ISSUE TITLE
model_path ignored when initializing a convokit.forecaster.CRAFTModel.CRAFTModel

### ISSUE THREAD

**Issue by jschluger** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#39]
## Overview
The behavior of the `model_path` parameter in initilization of a `convokit.forecaster.CRAFTModel.CRAFTModel` object is quite surprising and seems incorrect.

## Specifics
Consider this code:
```
from convokit.forecaster.CRAFTModel import CRAFTModel
CRAFT_model = CRAFTModel(device_type="cpu", model_path="model_cmv.tar")
```
Running this code if `model.tar` is not a file in the current directory leads to the output
```
Initializing CRAFT model with options:
{'hidden_size': 500, 'encoder_n_layers': 2, 'context_encoder_n_layers': 2, 'decoder_n_layers': 2, 'dropout': 0.1, 'batch_size': 64, 'clip': 50.0, 'learning_rate': 1e-05, 'print_every': 10, 'train_epochs': 30, 'validation_size': 0.2, 'max_length': 80, 'trained_model_output_filepath': 'finetuned_model.tar'}
Could not find CRAFT model tar file at: model_cmv.tar
Loading saved parameters...
	Downloading trained CRAFT...
	...Done!
Building encoders, decoder, and classifier...
Models built and ready to go!
```
and the side affect of `model.tar` appearing in the working directory **regardless** of what you specify for the `model_path`.

On the other hand, if  `model.tar` is a file in the current directory leads to the output
```Initializing CRAFT model with options:
{'hidden_size': 500, 'encoder_n_layers': 2, 'context_encoder_n_layers': 2, 'decoder_n_layers': 2, 'dropout': 0.1, 'batch_size': 64, 'clip': 50.0, 'learning_rate': 1e-05, 'print_every': 10, 'train_epochs': 30, 'validation_size': 0.2, 'max_length': 80, 'trained_model_output_filepath': 'finetuned_model.tar'}
Could not find CRAFT model tar file at: model_cmv.tar
Loading saved parameters...
Building encoders, decoder, and classifier...
Models built and ready to go!
```
where the specified `model_path` is ignored (and presumably `model.tar` is used to load the model, since nothing is downloaded).

**Comment by calebchiam** [comment]
Thanks for pointing this out because it reminds me that we need to link to the documentation pages for the CRAFT Model from Forecaster more explicitly.

Take a look at: [the CRAFT Model documentation](https://zissou.infosci.cornell.edu/convokit/documentation/craftmodel.html) and that should answer your question about what model_path is for. 

The custom path setting for where the model should be downloaded to is something we're working on, pending some other discussions. Let me know if you have any other questions.

**Comment by jschluger** [comment]
I am not sure this resolves the issue. I am trying to use `model_path` for what the documentation describes it to be; I run the code include in the issue with a model_cmv.tar file in the working directory because that is the model I want to use.  (I need the model trained on the r/ChangeMyView corpus). However, that still leads to `model.cmv` being downloaded, and it is unclear which model is actually loaded to initialize the resulting CRAFTModel object. 

Maybe my model_cmv.tar file is not formatted in the way the initialization procedure expects?
I am downloading this trained model as `model_cmv.tar`: http://zissou.infosci.cornell.edu/convokit/models/craft_cmv/craft_full.tar

**Comment by calebchiam** [comment]
Could you share your directory setup? i.e. where the CRAFTModel initializer is run from, where the .tar file is with respect to it?

**Comment by calebchiam** [comment]
Actually, I think I see the issue -- there was indeed a missing 'not' in the check for an input path (https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/commit/2d9204d9340496f250069f0bf46e2aafbf3b1046). Sorry about that, please install convokit 2.3.0.3 and let me know if that fixes it for you.

**Comment by jschluger** [comment]
I have verified that the behavior is not a bug on my end by running just these two lines of code
```
from convokit.forecaster.CRAFTModel import CRAFTModel
CRAFT_model = CRAFTModel(device_type="cpu", model_path="model_cmv.tar")
``` 
in an iPython shell in a directory that contains model_cmv.tar.

Here is my terminal output for details:
```
(convo) ➜  spring_2020 ls
CRAFT-backend  CRAFT-frontend CRAFT-mod      model_cmv.tar
(convo) ➜  spring_2020 ipython
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from convokit.forecaster.CRAFTModel import CRAFTModel 
   ...: CRAFT_model = CRAFTModel(device_type="cpu", model_path="model_cmv.tar")                                                                                                      
Initializing CRAFT model with options:
{'hidden_size': 500, 'encoder_n_layers': 2, 'context_encoder_n_layers': 2, 'decoder_n_layers': 2, 'dropout': 0.1, 'batch_size': 64, 'clip': 50.0, 'learning_rate': 1e-05, 'print_every': 10, 'train_epochs': 30, 'validation_size': 0.2, 'max_length': 80, 'trained_model_output_filepath': 'finetuned_model.tar'}
Could not find CRAFT model tar file at: model_cmv.tar
Loading saved parameters...
	Downloading trained CRAFT...
	...Done!
Building encoders, decoder, and classifier...
Models built and ready to go!

In [2]:                                                                                                                                                                              
Do you really want to exit ([y]/n)? y
(convo) ➜  spring_2020 ls
CRAFT-backend  CRAFT-frontend CRAFT-mod      model.tar      model_cmv.tar
```

**Comment by jschluger** [comment]
Yes, this fixed the issue for me! Thanks for your quick bug fixing!
