### ISSUE TITLE
Metadata not saving

### ISSUE THREAD

**Issue by ddemszky** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#40]
Hi,
Thanks so much for this great toolkit!

I have encountered a couple of issues, I'd appreciate your help with solving these:
1) The conversation id (cid) is not saving when I dump the corpus.
2) After I dumped and loaded the corpus again, I am trying to add additional metadata to the utterances. I don't quite understand the difference between `utterance.add_meta()` and `utterance.set_info()`. It would be helpful to have examples using these functions.
3) I've created vector representations for the utterances, but it took me a while to figure out how to save, load and use them. Now I have it figured out, but I think it would be helpful to have examples in your documentation.

Thanks,
Dora

**Comment by calebchiam** [comment]
Hi Dora, thanks for raising these issues (and for trying out ConvoKit!)

1. Note that Conversation ids are defined by the .root field of Utterances. In other words, the set of keys in conversations.json will be the set of roots of the Utterances in the corpus. Let me know if that clarifies it (and feel free to share a code example for further diagnosing)

2. Functionally, the two are the same for now. `set_info()` is actually intended for storing text processing outputs (e.g. parses, vectors, etc), and in a future release, will be distinct from add_meta(). 

3. Is this what you had in mind? [Text Processors documentation (https://zissou.infosci.cornell.edu/convokit/documentation/text_processing.html) and ([example](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/text-processing/text_preprocessing_demo.ipynb)).

Happy to help with any other questions,
Caleb

**Comment by ddemszky** [comment]
And another thing I just noticed: when I dump the corpus, the info that I didn't load during that run (e.g. metadata about conversations) is not saved and overwrites the previously saved metadata with an empty file. This makes it difficult to keep adding more metadata, because I first need to load everything that I previously saved.

**Comment by ddemszky** [comment]
Thanks, Caleb, for the quick reply!

1. Yes, that makes sense.  However, I actually have my own IDs for the conversations and currently I'm only able to add my own IDs as metadata. This is fine, but perhaps it'd be great to say it explicitly (that even if I set the CID value, it will not save when the corpus is dumped). 

2. Great, that's helpful!

3. Yes, I saw this, but not quite. It would be helpful to see examples that are using the `set_vector_reprs()`, `dump_vector_reprs()`, etc.

Thanks again!

**Comment by calebchiam** [comment]
Re: 1, why not set your Conversation IDs as the root field for your Utterances? (And yes, I agree that that's worth making more explicit)

Re: 3, @tisjune might be able to clarify this further as she implemented this.

**Comment by tisjune** [comment]
Re: the disappearing metadata, I wonder if the `dump_info` function [here](https://zissou.infosci.cornell.edu/convokit/documentation/corpus.html#convokit.model.corpus.Corpus.dump_info) would be useful -- [this demo](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/text-processing/text_preprocessing_demo.ipynb), the section titled Storing and loading corpora, might help.

On vector representations, totally agree that having examples would be useful--thanks for the suggestion! As a half-answer, one example for i/o in [this notebook](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/prompt-types/prompt-type-demo.ipynb) under "storing vector representations" (however, if you wanted to know more about how the data is internally stored or how to access it for any vectorized operations, your best bet right now is to read the code--sorry about that!)

**Comment by tisjune** [comment]
@ddemszky just to briefly follow up -- handling the vector representations is something that's less-developed right now in terms of documentation and support, as you may have discovered, so if you had a particular use case in mind that either works well or poorly with what's presently available, please let us know!

**Comment by ddemszky** [comment]
Thanks, @calebchiam and @tisjune! :)

Regarding the vectors, I think that one thing that would be helpful is to have more documentation for and show multiple examples of how one can...
1) use custom functions to create embeddings for the vectors (including functions that are not part of scikit learn)
2) manipulate vectors as efficiently as one would in pandas / numpy (and also explain why is it easier / better for someone to use your toolkit for manipulating data as opposed to using pandas / numpy)

After spending some time with your code, it's possible to figure these things out. But right now I feel that the overhead for understanding how to work with the toolkit makes it seem much simpler to just use my own functions for data manipulation, and use your code for loading and storing the data. But if it were made simpler, I would be definitely ready to use your toolkit for data manipulation as well! Right now, even the ability to store and load data in a neat structured way with your toolkit is super helpful!

**Comment by calebchiam** [comment]
Thanks Dora! The feedback regarding vectors is super helpful. We'll update you again if / when we have implemented more vectors-friendly functionality and documentation.
