### ISSUE TITLE
Input format for inference

### ISSUE THREAD

**Issue by poornagurram** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#44]
The input format for inference in Politeness Strategies is pretty complex. Is there a way to get the politeness score with just text input ? Like it is in [here](http://politeness.cornell.edu/)

**Comment by calebchiam** [comment]
Hi @poornagurram, we do not offer the trained politeness model in the web app as a standalone module, but you can train such a model easily using the ConvoKit package. We recommend following the demo [here](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/politeness-strategies/politeness_demo.ipynb).

**Comment by binghesam** [comment]
Hi @poornagurram , do you find the solution to this problem? I am facing the same issue. Given a text, we want to get the politeness score. Many thanks.

**Comment by binghesam** [comment]
Hi @calebchiam , I read the above link you provided. I still cannot figure out how we provide the politeness score/category given a raw short text, for example, one tweet. In the example within the link, when we download the corpus, many associated files are provided with many json&jsonl files. But, in our case, we only have the raw tweet text. Can you give some advice on the pipeline for predicting the politeness score/category of one short tweet. Many thanks.
