### ISSUE TITLE
[dataset] GAP corpus dataset

### ISSUE THREAD

**Issue by ZiggyFloat** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#55]

**Comment by calebchiam** [comment]
Hi @ZiggyFloat, we're happy to work with you if you'd like to incorporate the GAP corpus into ConvoKit. If you haven't already, take a look at our [guide to contributing datasets](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/CONTRIBUTING.md#contributing-new-datasets) and let us know if you have any questions regarding ConvoKit.

**Comment by ZiggyFloat** [comment]
# Group Affect and Performance (GAP) Corpus

The Group Affect and Performance (GAP) Corpus has been collected at University of the Fraser Valley (UFV, Canada). The original dataset comprises of 28 group meetings of two to four group members, with a total of 84 participants. Group sizes vary from two to four participants. All the recorded conversations are in English. 

Group members must complete a Winter Survival Task (WST), a group decision-making exercise where participants must rank 15 items according to their importance in a hypothetical plane crash scenario. Participants first rank the items individually. Then, each group was given a maximum of 15 minutes to complete the WST. 

A full description of the dataset can be found here: 

[M. Braley and G. Murray, “The Group Affect and Performance (GAP) corpus,” in Proceedings of the Group Interaction Frontiers in Technology. ACM, 2018, p. 2.](https://www.ufv.ca/media/assets/computer-information-systems/gabriel-murray/publications/main-2.pdf)

Please cite this paper when using it in your research:
```
@inproceedings{gapcorpus18,
  title={The Group Affect and Performance (GAP) Corpus},
  author={Braley, McKenzie and Murray, Gabriel},
  booktitle={Proceedings of the ICMI 2018 Workshop on Group Interaction Frontiers in Technology (GIFT)},
  location={Boulder, CO},
  year={2018},
}
```
Contributed by: Uliyana Kubasova (uliyana.kubasova@student.ufv.ca)

## Dataset details

### Speaker-level information

Meeting and Group Member Identification (ID) Codes: For all corpus components, meetings and group members are identified with a code. Meetings are coded with a number based on the temporal order of data collection. Group members are coded with one of five arbitrarily assigned colors (i.e., blue, green, pink, orange, yellow).

Additional metadata includes:

- Year at UFV
- Gender
- English: first or second language
- AIS: Absolute Individual Score
- AII: Absolute Individual Influence
- Ind_TE: Time Expectations 
- Ind_WW: Worked Well Together
- Ind_TM: Time Management
- Ind_Eff: Efficiency
- Ind_QW: Overall Quality of Work
- Ind_Sat: Overall Satisfaction 
- Ind_Lead: Leadership
- Group Number


### Utterance-level information

Each utterance from the GAP corpus possesses the following informations, which are aligned with the Utterance schema from ConvoKit:

- idx: unique speaker utterance, e.g. 1.Green.70
- speaker: speaker name with group number, e.g. 1.Green
- root: id of the first utterance of each group, e.g. 1.Pink.1
- reply_to: previous idx, e.g. 1.Blue.105
- timestamp: start time in format HH:MM:SS
- text: sentence of utterance, without punctuation

Additional metadata includes:

- Duration: in seconds and milliseconds
- Sentiment: whether the sentence bears any positive or negative sentiment
- Decision: denotes a group-decision process -- possible values include Proposal, Acceptance, Rejection, and Confirmation
- Private: if the speaker is refering to a private item
- Survival Item: what survival item was mentioned

### Conversation-level information

Each conversation has the associated metadata:

- Group Number
- Meeting Size
- Meeting Length in Minutes
- AGS: Absolute Group Score
- Group_TE: Time Expectations
- Group_WW: Worked Well Together
- Group_TM: Time Management
- Group_Eff: Efficiency
- Group_QW: Overall Quality of Work
- Group_Sat: Overall Satisfaction

### Usage

To download directly with ConvoKit:
<pre><code>
>>> from convokit import Corpus, download
>>> gap_corpus = Corpus(filename=download("gap-corpus"))
</pre></code>

A quick summary:
<pre><code>
>>> gap_corpus.print_summary_stats()
>>> Number of Speakers: 84
>>> Number of Utterances: 8009
>>> Number of Conversations: 28
</pre></code>

### Additional note

#### Data License

The GAP corpus is released under the Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) license. https://creativecommons.org/licenses/by-nc/4.0/

### Contact

Please email any questions to: Uliyana Kubasova (uliyana.kubasova@student.ufv.ca)

[GAP ConvoKit.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/4853724/GAP.ConvoKit.zip)

**Comment by calebchiam** [comment]
Hi @ZiggyFloat, thanks for the contributing this dataset. I've been doing some checks on it and, overall, it looks great! I only have a few clarifying questions before we make it available for download in ConvoKit.

1. I've explored a few of the conversations and noticed that the "$" symbol often comes up in the Utterance text. Could you explain what this means? (You could add this to the Utterance-level information section assuming it's significant.)

2. In the corpus, the timestamp format seems to be HH:MM.[s] instead of HH:MM:SS. Which one should be used? If it's the former, a short note on how to understand [s] would be helpful.

3. Could you elaborate on some of the metadata fields for Speaker and Conversation? (The Utterance one is great.) Some of these fields are self-explanatory, but most of these need some additional clarification, e.g. what does Group_TE (Time Expectations) mean? What are the units used for these Group and Individual attributes and how are they measured? 

Let me know if you have any questions, thanks!

**Comment by ZiggyFloat** [comment]
Hi @calebchiam , thanks for the feedback!
I've updated the README.md and elaborated on the points you mentioned. Please let me know if you have any additional comments or suggestions.

Please find attached in the zip file:
1. README.md
2. Jupyter Notebook file showing how to convert the corpus into ConvoKit
3. Zipped corpus in ConvoKit format

[GAP ConvoKit.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/4865838/GAP.ConvoKit.zip)

**Comment by calebchiam** [comment]
Thanks @ZiggyFloat!

The dataset is now available for download under the name `gap-corpus`.

The documentation for it is available here: https://convokit.cornell.edu/documentation/gap.html

**Comment by calebchiam** [comment]
@all-contributors please add @ZiggyFloat for data

**Comment by calebchiam** [comment]
@all-contributors please add @ZiggyFloat for data

**Comment by calebchiam** [comment]
@all-contributors please add @ZiggyFloat for data

**Comment by calebchiam** [comment]
@all-contributors please add @ZiggyFloat for data
