### ISSUE TITLE
conversations-gone-awry-cmv-corpus is not loading

### ISSUE THREAD

**Issue by hadarishav** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#63]
Hi! When I am loading the CMV corpus It does not load and gives an error.

Code: ```corpus = Corpus(download('conversations-gone-awry-cmv-corpus'))```

Error: 'Lemmatizer' object has no attribute 'lookups'

**Comment by calebchiam** [comment]
I suspect this is a versioning issue with SpaCy -- the latest version is likely incompatible with the SpaCy object we've stored as binary metadata. @jpwchang, could you look into this?

**Comment by jpwchang** [comment]
Yup, seems this corpus was still using the old (spacy binaries) format for parse info as opposed to the new text-based format. I've updated the corpus to the new format and reuploaded it. @hadarishav, if you try again now it should work (ConvoKit should auto-detect that there is a new version of the corpus available and download it when you run `download('conversations-gone-awry-cmv-corpus')`)
