### ISSUE TITLE
Prompt types summarize vs. display_type

### ISSUE THREAD

**Issue by sophieball** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#64]
In the past a couple of days I was using `pt_model.summarize(corpus, k=25)` to display the prompt types from `PromptTypeWrapper`, but it always outputs `None`. Then I found in my old code that, when I followed the conversation gone awry notebook earlier, I used `pt_model.display_type` to print out the prompt types outputs. Now switching back to `display_type` gives me the long chunk of output. 

Just wondering why `summarize` is not working for me?

**Comment by tisjune** [comment]
Hmm -- I'm a little puzzled by this (summarize calls display_type, and on my end it seems like the PromptTypeWrapper demo notebooks that call summarize still work -- so I have no guesses yet for what might be going on). Just for reference, what's your call for pt_model.display_type?

**Comment by sophieball** [comment]
1. It's 
```  pt = PromptTypeWrapper(
      n_types=N_TYPES,
      use_prompt_motifs=False,
      root_only=False,
      questions_only=False,
      enforce_caps=False,
      min_support=2,
      min_df=2,
      svd__n_components=50,
      max_dist=2.,
      random_state=1000)```

2. I'm using the pip version.

**Comment by tisjune** [comment]
The demo notebooks (with summarize) might be using a slightly newer version of the code than the current pip version -- sorry about that! We'll actually release newer version via pip in the next few days, and will let you know then. In the meantime, I think it's fair to keep using display_types.

**Comment by sophieball** [comment]
Sounds good! Thanks for investigating into this =)

**Comment by calebchiam** [comment]
Hi @sophieball, just wanted to let you know that v2.4 is now live and you should be able to make use of `summarize`.
