### ISSUE TITLE
[dataset] updated GAP corpus

### ISSUE THREAD

**Issue by ZiggyFloat** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#66]
Updated ConvoKit version of the GAP corpus, to match the current status of the repository.

Changes to the individual and group level metadata as some erroneous values in the spreadsheets were fixed.

[gap-corpus.zip](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/files/5106220/gap-corpus.zip)

**Comment by calebchiam** [comment]
Hi @ZiggyFloat, I've checked the corpus you uploaded, but it seems to be identical to the one that's currently available for download. (It also isn't using the latest ConvoKit version, which will have the 'vectors' key in most of the component .json files.)
