### ISSUE TITLE
Merge Two Corpus

### ISSUE THREAD

**Issue by TaoRuan-Campus** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#70]
I am wondering whether there is going to be a standard method to merge two corpus if the format of them is the same?

**Comment by calebchiam** [comment]
You can use `corpus.merge()` or `corpus.add_utterances()`. Both methods do several (expensive) checks against overwriting of data, so if you know the utterances in your two corpora are disjoint, I recommend using corpus.add_utterances with `with_checks=False`.

**Comment by TaoRuan-Campus** [comment]
Thank you for your reply! I am trying to use your method but another problem occurs. As we know, different jupyter notebooks can share data like https://www.thetopsites.net/article/50952105.shtml however when I store Corpus in one notebook I ma not able to read the Corpus in another notebook. Do you happen to know how to solve this problem?

**Comment by TaoRuan-Campus** [comment]
![Screen Shot 2020-10-01 at 19 28 19](https://user-images.githubusercontent.com/55067404/94879042-59602280-041c-11eb-9bdb-2242cbc64527.png)

**Comment by TaoRuan-Campus** [comment]
<img width="740" alt="Screen Shot 2020-10-01 at 19 28 35" src="https://user-images.githubusercontent.com/55067404/94879059-6715a800-041c-11eb-964f-ce3c1bf2eb4e.png">

**Comment by TaoRuan-Campus** [comment]
<img width="869" alt="Screen Shot 2020-10-01 at 19 30 45" src="https://user-images.githubusercontent.com/55067404/94879138-a2b07200-041c-11eb-81be-f1e6b86aca77.png">

**Comment by TaoRuan-Campus** [comment]
As shown above, teh stored Pandas DataFrame can be read in the jupyter notebook, while all the Coupus cannot be found.

**Comment by TaoRuan-Campus** [comment]
@calebchiam  Thank you again. I decided to use `dump` function to

**Comment by calebchiam** [comment]
Hi @TaoRuan-Campus, `add_utterances()` takes in a list of utterances, not a Corpus. You can try passing in `list(FightinCorpus_Emergency_Reddit.iter_utterances())`. Read our documentation for more details: https://convokit.cornell.edu/documentation/corpus.html

**Comment by TaoRuan-Campus** [comment]
Thanks! I figured it out. Actually the `speaker` problem still exists and I seem to have to construct the `corpus_speakers `dictionary to provide the speaker infomation instead of using `generic_speaker`. I might not be correct but it seems that the speaker information is a must in `add_utterances()`.

**Comment by calebchiam** [comment]
That doesn't sound right actually. You should be able to construct two separate corpora and merge them as is if they already have Speaker information present for all their Utterances. (A `generic_speaker` should be sufficient.) I'm guessing that something might have gone wrong to the corpus construction process (you might want to inspect your utterances), but otherwise great if it works!

**Comment by TaoRuan-Campus** [comment]
@calebchiam Thank you and I will check later on. Another question I got is in the documentation when using Fightin's words method (https://convokit.cornell.edu/documentation/tutorial.html) it seems that the raw text data are fed into the algorithm. I am wondering whether it is the standard way to compare two corpus? Is preprocessing(remove stop words, stemming, etc.) necessary for it?

**Comment by calebchiam** [comment]
To compare two corpora, you'd typically merge the two corpora and distinguish one corpora's utterances from another using a field in the utterance metadata, e.g. `utterance.meta['corpora'] = 'corpora1'`. Then you can set the classes during the FightingWords fit step. 

Preprocessing is up to you, though the FightingWords algorithm is designed to make stopwords less common as the most salient terms (you may read the paper for more details).

**Comment by TaoRuan-Campus** [comment]
Thanks!
