### ISSUE TITLE
get_coefs_helper doesn't account for case where feature_names=None

### ISSUE THREAD

**Issue by emtseng** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#73]
Was trying to get coefficients from the logreg built into PairedPrediction without explicitly passing feature names from an accompanying vectorizer. Looks like when feature_names=None, the assert in get_coefs_helper causes the entire method to error out.

https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/b71dcfc74154c0514030457b365cfb511d5f4b57/convokit/classifier/util.py#L138

I was able to hack around this by getting the feature names from the vectorizer I used upstream, but it would be nice to have get_coefs() directly pull the feature names from the vectorizer vocabulary, [as is described in the docs](https://convokit.cornell.edu/documentation/pairedprediction.html?highlight=pairer#convokit.paired_prediction.pairedVectorPrediction.PairedVectorPrediction.get_coefs), or just to have this helper specifically account for feature_names=None.

**Comment by calebchiam** [comment]
Hi @emtseng, good catch. It looks like the best fix for this is to remove the statement about handling `feature_names=None` from the docs. PairedVectorPrediction doesn't have access to a vectorizer object, nor does it have access to the Corpus object in this method call (from which it could have fetched the vector matrix and used its columns as feature names), so it looks like the only option is for the user to input it themselves (as you did). 

Do let me know if you had other ideas for how we might do this though.

**Comment by calebchiam** [comment]
Amended the description for `get_coefs()` in the documentation.

**Comment by calebchiam** [comment]
@all-contributors please add @emtseng for bug.
