### ISSUE TITLE
Is there a way to change the cache directory?

### ISSUE THREAD

**Issue by abisee** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#75]
I've tried searching the docs but was unable to find it. Is there something I can do to set the download cache to be something other than `~/.convokit`? Thanks!

**Comment by calebchiam** [comment]
Hi @abisee, you can set the `data_dir` parameter in `download()` to configure the output location. (Check out the [docs](https://convokit.cornell.edu/documentation/util.html) for more details.)

**Comment by abisee** [comment]
Great, thanks! 

Is there a way to set it once (e.g. setting an environment variable), so I don't need to specify `data_dir` every time I use the `download()` function?

**Comment by calebchiam** [comment]
Unfortunately not, though note that if you've downloaded a Corpus `example-corpus` for the first time to a specified `data_dir` (aka `download('example-corpus', data_dir=[loc])`), future calls to `download('example-corpus')` will automatically use the `example-corpus` stored at `loc`.

However, if you wish to permanently change the download directory, that's not something we support. Typically, we'd imagine most users downloading corpora to a local directory and then loading corpora directly from said local directory (without using the `download` function). In other words, using `download()` is typically a one-time thing, for when you're first downloading the data to be worked with on your machine.

Would your workflow benefit significantly from allowing the default download directory to be permanently changed? We could include something like this in a future release if we see a common use case for it.
