### ISSUE TITLE
How to export the fightin' words plot to png file

### ISSUE THREAD

**Issue by TaoRuan-Campus** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#79]
Hello, I am wondering whether there is a way to export the Fightin' words plot to png file, such as something like plt.savefig() function?

**Comment by calebchiam** [comment]
Not directly supported in Convokit, but you can get the plot in a separate window that you should be able to save directly from. See [this](https://stackoverflow.com/questions/14261903/how-can-i-open-the-interactive-matplotlib-window-in-ipython-notebook) for more details.
