### ISSUE TITLE
Exporting trained Classifier model

### ISSUE THREAD

**Issue by mariadfnl** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#81]
I want to export a trained classifier model. 
When I use pickle or joblib, I get the following error:
`import joblib`
`PolitenessClassifier = clf`
`filename = 'politeness_classifier.sav'`
`joblib.dump(PolitenessClassifier, filename)`
**PicklingError: Can't pickle <function < lambda> at 0x000001F6CAD61160>: it's not found as __main__.< lambda>**

When I use json,  get the following error:
`import json`
`PolitenessClassifier = clf`
`with open('PolitenessClassifier.json', 'w') as outfile:`
`    json.dump(PolitenessClassifier, outfile)`
**TypeError: Object of type Classifier is not JSON serializable**

**Comment by calebchiam** [comment]
Instead of serializing the entire Classifier object, you should be saving/serializing the underlying Classifier model: see `classifier.get_model()`

**Comment by mariadfnl** [comment]
> Instead of serializing the entire Classifier object, you should be saving/serializing the underlying Classifier model: see `classifier.get_model()`

Thanks a lot that really helped :)
And think you for quick response
