### ISSUE TITLE
politeness: trained, exported classifier unable to handle impoliteness after importing

### ISSUE THREAD

**Issue by mariadfnl** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#82]
Hey, as you can read in the title, I've got an issue with importing the trained model.
I trained a politeness classification model and exported it using joblib in a jupyter notebook. 
When I load the trained model into a .py file at first sight everything seems to work well but it loses the ability to handle impolite texts. The model tries to categorize them as neutral or polite. This does not accure when I reload the exported data in the classifier object I used to train the model. 

Thanks in advance for the help :)

**Comment by calebchiam** [comment]
This seems like a issue that's external to ConvoKit. It might be joblib-related, so perhaps you could try pickling the sklearn model instead?

**Comment by Nuri22** [comment]
It seems that ConvoKit 2.4.3 no longer being compatible with spaCy. The required by ConvoKit shorthand 'en' for the English dictionary is obsolete and is no longer available.   Any solution for this problem. thanks
