### ISSUE TITLE
ConvoKit 2.4.3 no longer being compatible with spaCy

### ISSUE THREAD

**Issue by Nuri22** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#84]
It seems that ConvoKit 2.4.3 no longer being compatible with spaCy. The required by ConvoKit shorthand 'en' for the English dictionary is obsolete and is no longer available. Any solution for this problem. thanks

**Comment by calebchiam** [comment]
Thanks for highlighting this -- it seems that the new SpaCy 3.0 released last week has resulted in some breaking changes. If you install spacy version 2.3.5, things should work fine, but we'll update ConvoKit to be compatible with SpaCy 3.0 soon.

**Comment by jpwchang** [comment]
Hi @Nuri22,

The latest release, v2.4.4 (https://pypi.org/project/convokit/2.4.4/), is now compatible with SpaCy 3.0. After updating, you should be able to run convokit alongside the latest SpaCy without any issues.
