### ISSUE TITLE
Can not access https://convokit.cornell.edu/

### ISSUE THREAD

**Issue by HerrKrishna** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#93]
The Website https://convokit.cornell.edu/ can not be acccesed, as its certificate has expired.
That results in an error for the following code snippet:
 corpus = Corpus(filename=download(corpus_name))

Error:

requests.exceptions.SSLError: HTTPSConnectionPool(host='zissou.infosci.cornell.edu', port=443): Max retries exceeded with url: /convokit/datasets/download_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')))

**Comment by cristiandnm** [comment]
thanks for the note! the certificate seems to have expired and we'll be fixing it shortly.

**Comment by HerrKrishna** [comment]
I can now access https://convokit.cornell.edu/ but i still get the sane error for
corpus = Corpus(filename=download(corpus_name))

**Comment by cristiandnm** [comment]
Could you please try again now (some other certificates needed to be updated).

**Comment by HerrKrishna** [comment]
Now it works. Thanks :)
