### ISSUE TITLE
Data formatting : collective emails

### ISSUE THREAD

**Issue by lbocken** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#95]
Hello,

I have a corpus of several collective emails with one sender and several receivers.

I do not know what is the best way to manage that in the data format of Convokit. Could you confirm that it is the good path :

body | sender | receiver | id
-- | -- | -- | --
xxxxxxxxxxxxxxx | @ | @1@2 | 45
  |   |   |  
xxxxxxxxxxxxxxx | @ | @1 | 45
xxxxxxxxxxxxxxx | @ | @2 | 45

Thank you very much for your help !

**Comment by calebchiam** [comment]
The `reply_to` field in the `Utterance` object holds an `Utterance` id, so technically the fact that there are multiple receivers should not have any implications for your Utterance object -- you can just include the list of receivers as a metadata attribute.

You can read about ConvoKit's [architecture](https://convokit.cornell.edu/documentation/architecture.html) and [corpus component classes](https://convokit.cornell.edu/documentation/model.html) for more details.
