### ISSUE TITLE
WikiConv example Jupyter NoteBook Code not working

### ISSUE THREAD

**Issue by ErikJSchmidt** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#96]
# Situation
Hey there, I am want to work with the WikiConv corpus and think the ConvoKit framework should make that a lot easier.
To get started I tried to follow along the [example notebook](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/dataset-examples/wikiconv/Create_Conversations_Script.ipynb). I downloaded the 2003 corpus on my machine via 
corpus_dir_path_cluster = "my/path/"

wikiconv_2003 = Corpus(filename=download("wikiconv-2003", data_dir = corpus_dir_path_cluster))

And started copying the code from the notebook into a python file step by step to make it work.
Now when using `print_final_conversation` everything works fine as long as the modification, deletion and restoration lists are not used. 

# The problem
No for example when I only put conversation with id `'1275892.3573.3573'` in the `random_conversations` list like:
`random_conversations = [wikiconv_2003.get_conversation('1275892.3573.3573')]`

and call
`print_final_conversation(random_conversations,  wikiconv_2003)`

then we get into function `check_lists_for_match` with param str(utterance) =
 `Utterance(id: '1277066.3845.3845', conversation_id: 1275892.3573.3573, reply-to: 1275892.3573.3573, speaker: Speaker(id: Ruhrjung, vectors: [], meta: {'user_id': '10582'}), timestamp: 1060644108.0, text: 'Germany is no state of USA. That is established, even in Wikipedia_talk:Naming_conventions_(city_names), where virtually no arguments for the comma-notion are presented, although the debate there seems to have fallen asleep (about July 22nd). ', vectors: [], meta: {'is_section_header': False, 'indentation': '1', 'toxicity': 0.0887862, 'sever_toxicity': 0.01593855, 'ancestor_id': '1275929.3845.3845', 'rev_id': '1275929', 'parent_id': None, 'original': ({'id': '1275929.3845.3845', 'root': '1275892.3573.3573', 'reply_to': '1275892.3573.3573', 'timestamp': 1060640971.0, 'text': 'Germany is no state of USA. That is established, even in Wikipedia_talk:Naming_conventions_(city_names), where virtually no arguments for the comma-notion are presented, although the debate there seems to have fallen asleep. ', 'meta': {'is_section_header': False, 'indentation': '1', 'toxicity': 0.0887862, 'sever_toxicity': 0.01593855, 'ancestor_id': '1275929.3845.3845', 'rev_id': '1275929', 'parent_id': None, 'original': None, 'modification': [], 'deletion': [], 'restoration': []}}), 'modification': [({'id': '1277066.3845.3845', 'root': '1275892.3573.3573', 'reply_to': '1275892.3573.3573', 'timestamp': 1060644108.0, 'text': 'Germany is no state of USA. That is established, even in Wikipedia_talk:Naming_conventions_(city_names), where virtually no arguments for the comma-notion are presented, although the debate there seems to have fallen asleep (about July 22nd). ', 'meta': {'is_section_header': False, 'indentation': '1', 'toxicity': 0.06772689, 'sever_toxicity': 0.009684636, 'ancestor_id': '1275929.3845.3845', 'rev_id': '1277066', 'parent_id': '1275929.3845.3845', 'original': None, 'modification': [], 'deletion': [], 'restoration': []}})], 'deletion': [], 'restoration': []})
`

and therefore str(modification_list) =
`Modifications[({'id': '1277066.3845.3845', 'root': '1275892.3573.3573', 'reply_to': '1275892.3573.3573', 'timestamp': 1060644108.0, 'text': 'Germany is no state of USA. That is established, even in Wikipedia_talk:Naming_conventions_(city_names), where virtually no arguments for the comma-notion are presented, although the debate there seems to have fallen asleep (about July 22nd). ', 'meta': {'is_section_header': False, 'indentation': '1', 'toxicity': 0.06772689, 'sever_toxicity': 0.009684636, 'ancestor_id': '1275929.3845.3845', 'rev_id': '1277066', 'parent_id': '1275929.3845.3845', 'original': None, 'modification': [], 'deletion': [], 'restoration': []}})]`

That leads to the check
`if (utterance_val.id == next_utterance_value.reply_to):`

that produces 
`AttributeError: 'Utterance' object has no attribute '_id'`

# My insights so far
When looking at the modifications list I see `'id': '1277066.3845.3845'` which I guess should correspond to the utterance's _id. So I don't get why the id is said to be missing.
I am not to familiar with Python, but I wonder why str(utterance) has the id printed as `id: '1277066.3845.3845'` without '' while the utterance in the modification list has `'id': '1277066.3845.3845'` where id is wrapped in  ''. To me it looks like the utterances in the modification list are in a json like format and I don#t know why.

Also the notebokk was update last in Nov 20, 2019 while the wikiconv models where updated last on Dec 1, 2020. So maybe the notebook is outdated?

# Conclusion
It would help me a lot if anyone could check if they can reproduce this AttributeError, or if this is a problem sole for me.

Thank you all for your help.

**Comment by jpwchang** [comment]
As of 03/21/2022, the ConvoKit WikiConv corpora have been updated so the modification metadata now work correctly, so the workaround described in the last comment is no longer needed.
