### ISSUE TITLE
request for collaborator in my study

### ISSUE THREAD

**Issue by annaksig** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#97]
Good morning all. I am a PhD researcher using Convokit. I am looking for a collaborator in my study analysis with ConvoKit. It has been really difficult to find anyone on other platforms. That is why I am addressing here. The collaborator will be second author in the paper. Please let me know. I am sorry I posted under 'issues', but it is quite urgent. In case they do not want to be co-authors, it can be undertaken as a paid job.Please reply here or email me at: ax23@kent.ac.uk

**Comment by calebchiam** [comment]
Hi Anna, I'm sorry to hear you're having trouble finding someone to work with you on this. ConvoKit should be picked up relatively easily by any experienced programmers or with some (initial) difficulty for novice programmers. As this is not the right platform for this, I'll be closing this issue, however the other ConvoKit developers and I have seen your request and will reach out to you if we can offer help.
