### ISSUE TITLE
Issues in installation

### ISSUE THREAD

**Issue by aljanaidehosu** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#98]
When I try: pip3 install convokit, I get the following error:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1rjvi1tt/spacy/setup.py", line 5, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

I have Python 3.6.2 installed, and numpy is also installed.

How can I fix this?

**Comment by calebchiam** [comment]
If I had to guess, your pip3 likely does not point to your Python 3.6.2 environment. I would suggest initialising and activating an virtualenv to install ConvoKit in.

**Comment by aljanaidehosu** [comment]
> If I had to guess, your pip3 likely does not point to your Python 3.6.2 environment. I would suggest initialising and activating an virtualenv to install ConvoKit in.


Thanks for your reply! I actually do use virtual env. These are the steps I follow:

conda create --name convokit2 python=3
source activate convokit
pip3 install convokit

**Comment by calebchiam** [comment]
Hmm, I'm not sure what the issue is then, I just ran your sequence of commands (correcting the second line to 'convokit2') and it worked just fine for me.

**Comment by aljanaidehosu** [comment]
So I managed to resolve this issue by running the command: python3 -m pip install --upgrade pip setuptools wheel
