### ISSUE TITLE
Adding a new dataset

### ISSUE THREAD

**Issue by kushalchawla** [CornellNLP/Cornell-Conversational-Analysis-Toolkit#99]
Hi. Is the Toolkit still accepting new datasets or is it deprecated? I would like to add our new dataset in negotiation dialogues, published at NAACL 2021: https://aclanthology.org/2021.naacl-main.254.pdf

Let me know! Thanks.

**Comment by calebchiam** [comment]
Hi @kushalchawla, yes we still accept new datasets! Please follow the [contributing guide](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/CONTRIBUTING.md) to make a dataset submission.

**Comment by kushalchawla** [comment]
Great! Thanks for letting me know. I will get to it.
